# Generated by Django 4.1.2 on 2022-10-26 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(),
        ),
    ]
